---
- hosts: managernode
  become: yes
  remote_user: azureuser
  tasks:
  - name: Update Packages
    ansible.builtin.apt:
      name: "{{ item }}"
      update_cache: yes
    loop:
      - rsyslog
      - nagios-nrpe-server
      - monitoring-plugins
      - apache2
      - php